apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: app
  labels:
    app.kubernetes.io/name: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
